version: "3.7"

services:
  consul:
    image: consul
    ports:
      - "8500:8500"
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      - stack

  rabbit:
    image: bmakarewicz/rabbitmq:latest
    build:
      context: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - stack
    hostname: rabbit
    depends_on:
      - consul

  cloud-config-service:
    image: bmakarewicz/cloud-config-service:latest
    build:
      context: cloud-config-service
    environment:
      - GIT_URI=https://github.com/bartlomiejmakarewicz/cloud-config.git
    ports:
      - "8888:8888"
    networks:
      - stack
    depends_on:
      - consul

  demo-consul:
    image: bmakarewicz/demo-consul:latest
    build:
      context: demo-consul
    ports:
      - "8080:8080"
    networks:
      - stack
    depends_on:
      - consul
      - cloud-config-service
      - rabbit

networks:
  stack:
